---
- name: Gather facts and display hostname, IP address, and OS version
  hosts: all
  gather_facts: true
  tasks:
    - name: Display hostname, IP address, and OS version
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_facts['hostname'] }}"
          - "IP Address: {{ ansible_facts['default_ipv4']['address'] }}"
          - "OS Version: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
