---
- name: Run Portainer agent container
  hosts: all:!pxmve,!vu22
  become: true

  tasks:
    - name: Start Portainer agent container
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:2.17.1
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports: "{{ '9002:9001' if inventory_hostname == 'rpi16' else '9001:9001' }}"
