# deploy_syncthing.yml
---

- name: Deploy Syncthing using Docker
  hosts: nuc115

  roles:
    - docker

  tasks:
    - name: Include encrypted secrets
      ansible.builtin.include_vars:
        file: ../roles/docker/vars/secrets.yml
        name: secrets

    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Deploy Syncthing container
      community.docker.docker_container:
        name: syncthing
        image: lscr.io/linuxserver/syncthing:latest
        hostname: "{{ inventory_hostname }}"
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "{{ secrets.puid }}"
          PGID: "{{ secrets.pgid }}"
          TZ: "{{ secrets.tz }}"
        volumes:
          - "~/apps/data/syncthing:/config"
          - "~/apps/secrets:/secrets"
          - "~/apps/backups:/backups"
        ports:
          - "8384:8384"
          - "22000:22000/tcp"
          - "22000:22000/udp"
          - "21027:21027/udp"
