---
- name: Deploy Telegraf in Docker container
  hosts: docker_hosts
  become: true
  roles:
    - docker

  tasks:

    - name: Include encrypted secrets
      ansible.builtin.include_vars:
        file: ../roles/docker/vars/secrets.yml
        name: secrets
      notify: Restart Telegraf

    - name: Ensure /etc/telegraf directory exists
      ansible.builtin.file:
        path: /etc/telegraf
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy Telegraf configuration
      ansible.builtin.copy:
        src: ../roles/docker/files/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart telegraf

    - name: Run Telegraf container
      community.docker.docker_container:
        name: telegraf
        image: "telegraf:latest"
        state: started
        pull: true
        restart_policy: always
        recreate: true
        hostname: "{{ inventory_hostname }}"
        env:
          TELEGRAF_PUBLISH_ADDRESS: "{{ secrets.telegraf_publish_address }}"
          INFLUX_TOKEN: "{{ secrets.INFLUX_TOKEN }}"
          USER: "{{ ansible_user }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
        labels:
          com.docker.compose.project: ansible-utils
      tags:
        - telegraf
      notify:
        - Restart telegraf
