---
- name: Deploy Syncthing using Docker
  hosts: docker_hosts

  roles:
    - docker

  tasks:
    - name: Include encrypted secrets
      ansible.builtin.include_vars:
        file: ../roles/docker/vars/secrets.yml
        name: secrets

    - name: Deploy Syncthing container
      community.docker.docker_container:
        name: syncthing
        image: lscr.io/linuxserver/syncthing:latest
        restart_policy: unless-stopped
        env:
          PGID: "{{ secrets.pgid }}"
          PUID: "{{ secrets.puid }}"
          TZ: "{{ secrets.tz }}"
        hostname: "{{ inventory_hostname }}"
        labels:
          com.docker.compose.project: ansible-utils
        ports:
          - "8384:8384"
          - "21027:21027/udp"
          - "22000:22000/tcp"
          - "22000:22000/udp"
        pull: true
        recreate: true
        state: started
        volumes:
          - "~/apps/data/syncthing:/config"
          - "~/apps/secrets:/secrets"
          - "~/apps/backups:/backups"
