---
- name: Run Portainer agent container
  hosts: docker_hosts

  roles:
    - docker

  tasks:
    - name: Start Portainer agent container
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: always
        pull: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports: "{{ '9002:9001' if inventory_hostname == 'rpi16' else '9001:9001' }}"
        labels:
          com.docker.compose.project: ansible-utils
