---
- name: Deploy Samba using Docker role
  hosts: docker_hosts

  roles:
    - docker

  tasks:
    - name: Include encrypted secrets
      ansible.builtin.include_vars:
        file: ../roles/docker/vars/secrets.yml
        name: secrets

    - name: Deploy Samba container
      community.docker.docker_container:
        name: samba
        image: dperson/samba
        state: started
        restart_policy: unless-stopped
        pull: true
        tty: true
        ports:
          - "137:137/udp"
          - "138:138/udp"
          - "139:139/tcp"
          - "445:445/tcp"
        env:
          TZ: "{{ secrets.tz }}"
          USERID: "{{ secrets.puid }}"
          GROUPID: "{{ secrets.pgid }}"
        volumes:
          - "/home/bri:/home:z"
        command: >
          -w "WORKGROUP"
          -u "{{ secrets.samba_user }};{{ secrets.samba_password }}"
          -s "home;/home;yes;no;no;{{ secrets.samba_user }};{{ secrets.samba_user }};{{ secrets.samba_user }}"
          -p
        labels:
          com.docker.compose.project: ansible-utils
