---
# tasks file for ubuntu_common
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"